### PR TITLE
EventDSL: Cache hostname

### PR DESCRIPTION
**Pull request by jasonf20**
Hi,

We are trying to improve our overall performance and one thing we noticed which can easily be done to help is cache the host name in the EventDSL class. Since this class is created often and the hostname rarely ever changes.

Let me know if there are any issues with this, otherwise I would appreciate you merging this :)

### CODE REVIEW

**Comment by aphyr** [comment]
On phone so I don't have a link handy but the comments in the other PR for hostname caching apply--we've got this in... I think riemann.common right now and should pull that logic down here into the java client. Notably, we need to handle hostname changes via periodic cache refreshing, and optionally shell out to `hostname` because the JVM can do weird things like DNS lookups instead of using gethostname(2).
On Feb 3, 2016 08:02, Jason Fine <notifications@github.com> wrote:Hi,

We are trying to improve our overall performance and one thing we noticed which can easily be done to help is cache the host name in the EventDSL class. Since this class is created often and the hostname rarely ever changes.

Let me know if there are any issues with this, otherwise I would appreciate you merging this :)



You can view, comment on, or merge this pull request online at:
  https://github.com/aphyr/riemann-java-client/pull/70

Commit Summary
EventDSL: Cache hostname

File Changes

    M
    riemann-java-client/src/main/java/com/aphyr/riemann/client/EventDSL.java
    (24)
  

Patch Links:
https://github.com/aphyr/riemann-java-client/pull/70.patchhttps://github.com/aphyr/riemann-java-client/pull/70.diff

**Comment by jasonf20** [comment]
@aphyr I see (didn't notice the other pull request). However it seems like you were interested in merging pr #47 and then it was just closed without merging, even though it was agreed that it improved the current situation.

Any reason for this?

**Comment by aphyr** [comment]
Bunch of issues w.r.t. concurrency that the author never addressed, IIRC. It sat stale for a few months and I think I gave up. Don't precisely recall.
On Feb 3, 2016 9:10 AM, Jason Fine <notifications@github.com> wrote:@aphyr I see (didn't notice the other pull request). However it seems like you were interested in merging pr #47 and then it was just closed without merging, even though it was agreed that it improved the current situation.

Any reason for this?

**Comment by jasonf20** [comment]
Will my pull request be good enough if I change it to update every minute
via checking against currentTimeMilli? It won't cover all you discussed
there but it will be much better than the current situation.

Alternatively I can simply make the host name come from an override able
function. And in my code where I don't care about updates override it.

**Comment by aphyr** [comment]
CurrentTimeMilli is nonmonotonic, so you probably want nanoTime, and you'll need a mutex or atomic ref to prevent threads racing on the refresh. I'd really like to avoid having a bunch of reimplementions of this so I'd prefer a port of the current logic from riemann.common, but I'll take incremental improvements for sure.
On Feb 3, 2016 11:41 AM, Jason Fine <notifications@github.com> wrote:Will my pull request be good enough if I change it to update every minute
via checking against currentTimeMilli? It won't cover all you discussed
there but it will be much better than the current situation.

Alternatively I can simply make the host name come from an override able
function. And in my code where I don't care about updates override it.

**Comment by jasonf20** [comment]
Yea sure, ill get something done tomorrow. Just a quick incremental
improvement as you said.

**Comment by jasonf20** [comment]
@aphyr Quickly added the updating. It's not perfect but for now it should be much better than the existing code in terms of performance.

**Comment by jamtur01** [comment]
@jasonf20 Sorry about the long gap in response! Any chance you could rebase this? Thanks!

**Comment by jasonf20** [comment]
@jamtur01 Hi, I don't really need this anymore, but I rebased it for you :) enjoy.

**Comment by jamtur01** [comment]
Thanks @jasonf20 much appreciated!

**Comment by jamtur01** [comment]
Closing.

**Pull request closed without merging**
