### PR TITLE
[Work in progress] use Netty 4

### PR DESCRIPTION
**Pull request by mcorbin**
#73

Disclaimer : I never used Netty before.

This is a tentative to update the client to Netty 4. This code compile but doesn't work.
My biggest problem is with the TcpHandler (my code is wrong) :

The Netty 3 code extends SimpleChannelHandler, and override **handleDownstream** and **messageReceived**. I cannot reproduced this behavior in Netty 4 because SimpleChannelHandler not longer exists. In other classes, **handleDownstream** is now divided into several methods (in ChannelOutboundHandlerAdapter for example, we can use the **write** method if i understand correctly), and **messageReceived** is now (i think) channelRead0 (in **SimpleChannelInboundHandler**)

 I tried to use ChannelOutboundHandlerAdapter, SimpleChannelInboundHandler etc... but it is not working. I think it is because the Inbound/Outbound separation in Netty 4. 

I opened the PR so you can look at my code, i need help from someone with netty skills ;)

### CODE REVIEW

**Comment by mcorbin** [comment]
I updated the commit, my client almost works.
2 tests are failing : 

- In BatchClientPromiseTest.java, this test fail : 
```java
Msg rsp = promises.get(i).deref(10, TimeUnit.MILLISECONDS,
                                        Msg.newBuilder().setOk(false).build());
        assertTrue(!rsp.hasOk() || rsp.getOk());
```
I don't understand what is tested here. What is setOk(false) on the builder ?

- In TcpClientTest, limiterLeakTest() is failing, i don't really know why.

can someone take a look at this ?

**Comment by jamtur01** [comment]
@mcorbin Do you fancy rebasing this and seeing if we can't get the last few tests fixed?

**Comment by mcorbin** [comment]
@jamtur01 i will try to rebase (probably next week). But i will also need help from someone knowing Netty, because i'm not sure about what i'm doing here (and netty official documentation is nonexistent). Furthermore, i don't fully understand the async/promise system added on top of Netty in the Riemann client.

**Comment by jamtur01** [comment]
Superseded by #91 - Thanks!

**Pull request closed without merging**
