### PR TITLE
Preparations for a Netty 4 client

### PR DESCRIPTION
**Pull request by markdingram**
- RiemannClient now creates transports via TcpTransport & UdpTransport factories,
  defaulting to the existing Netty3 impl's
- Move classes that reference org.jboss.netty package into io.riemann.riemann.client.netty3 package

### CODE REVIEW

**Comment by jamtur01** [comment]
I don't know Netty 4 well either I am afraid. @aphyr?

**Comment by markdingram** [comment]
I'm afraid there's no Netty 4 in this PR, but it prepares the ground for a future PR that would add the corresponding io.riemann.riemann.client.netty4 package with an (optional) dependency on Netty 4. For the foreseeable future I would envisage the existing Netty3 being the default impl as the Netty 4 impl matures.

**Comment by mcorbin** [comment]
> I'm afraid there's no Netty 4 in this PR, but it prepares the ground for a future PR that would add the corresponding io.riemann.riemann.client.netty4 package with an (optional) dependency on Netty 4

Yeah, I thought about the future ;) I don't know Netty 3 either :D

**Comment by markdingram** [comment]
Maybe this approach was more complex than warranted, closing in favour of #91

**Pull request closed without merging**
